updated gifs
ipinfo/cli pull request #86
Opened 2021-12-20 14:16 UTC by talhahwahla

replaced older gifs with newer ones. these ones show the latest info and are generated with asciinema.

2021-12-20 14:37 UTC, rm-Umar requested changes

2021-12-20 14:37 UTC, rm-Umar commented on gif/README.md
> +
```suggestion
```

2021-12-20 14:37 UTC, rm-Umar commented on gif/README.md
> +https://dstein64.github.io/gifcast/
``` suggestion
https://dstein64.github.io/gifcast/.
```

2021-12-20 14:37 UTC, rm-Umar commented on gif/README.md
> +The program uses asciinema to generate .cast files and renders them with
```suggestion 
The program uses `asciinema` to generate `.cast` files and renders them with

2021-12-20 14:37 UTC, rm-Umar commented on gif/README.md
> +The program uses asciinema to generate .cast files and renders them with
You mentioned `The program uses` but there's no program in the PR. Are you using some custom program that uses `asciinema`? if yes then mention the program also. If you are using `asciinema` to generate `.cast` files then mention it clearly.

2021-12-20 14:49 UTC, rm-Umar requested changes
The gifs are too big, should reduce the font size.
Links are broken in `Any IP`, `Piping` (both `cat.gif` and `cat-csv.gif`), and `Field Filter` sections. kindly update the links in the readme file or map the file names according to the readme.

2021-12-21 08:05 UTC, rm-Umar commented
Seems good! Thank you @talhahwahla for your contribution!

2021-12-21 08:05 UTC, rm-Umar approved these changes

2021-12-21 08:09 UTC, rm-Umar requested changes
@talhahwahla one last thing and then we are done.

2021-12-21 08:09 UTC, rm-Umar commented on gif/README.md
> +Asciinema is used to generate the `.cast` files. These `.cast` files are rendered into
```suggestion
`Asciinema` is used to generate the `.cast` files. These `.cast` files are rendered into 
```

2021-12-21 08:18 UTC, rm-Umar approved these changes

2021-12-21 08:18 UTC, merged

2021-12-21 09:20 UTC, talhahwahla commented
You are welcome!